---
title: Translating for the Raspberry Pi Foundation
hero_image: images/banner.png
description: getting-started-with-translation description
version: 4
listed: false
copyedit: false
last_tested: '2019-01-23'
steps:
- title: Introduction
  completion: engaged
- title: What we translate
- title: Workflow
- title: Tools
- title: Support
- title: What's in it for you
  completion: internal
- title: Next steps
