title: translating-for-raspberry-pi
hero_image: images/banner.png
description: translating-for-raspberry-pi description
version: 4
listed: false
copyedit: false
last_tested: "2019-05-15"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
